name: Maven Build on Commit

on: [push]

jobs:

  common-setup:  # Étape commune pour la récupération du code source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

  test:
    needs: common-setup  # Ce travail dépend de l'étape "common-setup"
    runs-on: ubuntu-latest

    steps:
      - name: Run Maven Tests
        run: mvn clean test

  package:
    needs: common-setup  # Ce travail dépend de l'étape "common-setup"
    runs-on: ubuntu-latest

    steps:
      - name: Maven Build
        run: mvn clean package -DskipTests
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packaged-artifact
          path: target/*.jar

  docker-build-and-push:
    needs: package
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: packaged-artifact
          path: target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: raloute/java:${{ github.sha }}
          build-args: JAR_FILE=target/plages-0.0.1-SNAPSHOT.jar
